WIP: Khjobs crd
Comcast/kuberhealthy pull request #584
Opened 2020-07-31 19:51 UTC by joshulyne

2020-08-10 21:19 UTC, integrii commented on pkg/checks/external/main.go
> +func New(client *kubernetes.Clientset, checkConfig *khcheckcrd.KuberhealthyCheck, jobConfig *khjobcrd.KuberhealthyJob, khCheckClient *khcheckcrd.KuberhealthyCheckClient, khStateClient *khstatecrd.Kub
Consider refactor to `NewChecker` and `NewJob` funcs.   This lets us remove the `khjob bool` from this function signature.  New checks will continue to call `New` and `New` will simply call `NewChecker`.  Likewise, `NewJob` will create a new job.

2020-09-03 21:07 UTC, joshulyne commented on cmd/kuberhealthy/kuberhealthy.go
> +	if khWorkload == health.KHCheck {
test for empty khworkload -- or use switch case

2020-09-03 21:07 UTC, joshulyne commented on cmd/kuberhealthy/kuberhealthy.go
> +	if khWorkload == health.KHCheck {
return an error up

2020-09-03 21:09 UTC, joshulyne commented on cmd/kuberhealthy/kuberhealthy.go
> +func determineKHWorkload(name string, namespace string) health.KHWorkload {
comment on this function

2020-10-06 18:17 UTC, integrii requested changes

2020-10-06 18:17 UTC, integrii commented on cmd/kuberhealthy/Makefile
> +TAG="v2.4.0"
```suggestion
TAG="latest"
```

Let's move this to `latest` and only tag images with release versions when we do a release.  In the future, we will just make new builds of kuberhealthy use a commit hash until a release is cut.

2020-10-06 18:19 UTC, integrii approved these changes
LGTM.  Feel free to merge after enough in-cluster testing looks good.  👍 🥳

2020-10-15 20:08 UTC, merged