Release process doc
Comcast/kuberhealthy pull request #589
Opened 2020-08-04 18:12 UTC by joshulyne

2020-08-05 19:34 UTC, integrii commented
We should see what happens to our automatic container builds before we fully finish this document.

2020-08-18 18:58 UTC, chadbitzer commented
Hold on merging this, I'm adding notes how Helm repo is publshed.

2020-09-03 21:12 UTC, chadbitzer approved these changes

2020-09-15 23:16 UTC, integrii requested changes

2020-09-15 23:16 UTC, integrii commented on docs/RELEASE.md
> +
What about creating a tag in github?  This says to publish notes, but does not talk about the tag that gets created.

2020-09-15 23:16 UTC, integrii commented on docs/RELEASE.md
> +7. Write up and publish release notes, giving an update / latest changes from the last release: new *Kuberhealthy Checks* (if any), new *Features*, and *Bug Fixes*
```suggestion
7. Write up release notes, giving an update / latest changes from the last release: new *Kuberhealthy Checks* (if any), new *Features*, and *Bug Fixes*.  Go into Github and create a new release with the appropriate version and change notes in the body.
```

2021-01-08 01:22 UTC, integrii commented
@joshulyne I think this updated README is valid given our new build processes and automation.  More work would be great to automate the tagging and pushing of versioned images, but this process should be accurate to current day.

2021-01-08 02:00 UTC, joshulyne commented on docs/RELEASE.md
> +    docker push kuberhealthy/kuberhealthy:v2.3.4
```suggestion
    docker tag kuberhealthy/kuberhealthy:latest kuberhealthy/kuberhealthy:{release_version}
    docker push kuberhealthy/kuberhealthy:{release_version}
```

2021-01-08 02:01 UTC, joshulyne commented on docs/RELEASE.md
> +    docker push kuberhealthy/kuberhealthy:v2.3.4
this is just a nitpick suggestion

2021-01-22 20:51 UTC, merged