Daemonset update and bug fix
Comcast/kuberhealthy pull request #725
Opened 2020-11-10 22:08 UTC by rickkkkc137

2020-11-10 22:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Comcast/kuberhealthy?pullRequest=725) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Comcast/kuberhealthy?pullRequest=725) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Comcast/kuberhealthy?pullRequest=725) it.</sub>

2020-11-12 18:26 UTC, jonnydawg commented on cmd/daemonset-check/input.go
> +							Operator: "Equal",
try using `corev1.TolerationOpEqual`

2020-11-12 18:34 UTC, jonnydawg commented on cmd/daemonset-check/input.go
> +							Value: splitkv[1],
same here

2020-11-12 18:35 UTC, jonnydawg commented on cmd/daemonset-check/input.go
> +						Operator: "Exists",
there's a `corev1.TolerationOpExists` as well

2020-11-12 18:35 UTC, jonnydawg commented on cmd/daemonset-check/input.go
> +				Operator: "Exists",
and same here as above

2020-11-12 18:58 UTC, rjacks161 commented on cmd/daemonset-check/input.go
> +							Operator: "Equal",
Added these

2020-11-17 18:41 UTC, jonnydawg approved these changes
Looks good! Thanks for doing this!

2020-11-17 18:45 UTC, jonnydawg commented
Make sure to change the tag value for the daemonset-check in the makefile

2020-11-18 19:51 UTC, integrii commented
re-running jobs with @jonnydawg's fix merged

2020-11-19 19:06 UTC, integrii requested changes

2020-11-19 19:06 UTC, integrii commented on cmd/daemonset-check/daemonset-check.yaml
> +            value: "kubernetes.io/hostname=test"
TODO: add node selector example and comment out both env vars by default

2020-11-20 17:49 UTC, integrii approved these changes

2020-11-23 22:54 UTC, jonnydawg reviewed
small changes requested, but looks good!

2020-11-23 22:54 UTC, jonnydawg commented on cmd/daemonset-check/create_toleration_test.go
> +	//string_tol := "blah"
could we remove these comments?

2020-11-23 22:54 UTC, jonnydawg commented on cmd/daemonset-check/input.go
it'd be nice to have comments for these functions :)

2020-11-24 18:46 UTC, jonnydawg approved these changes

2020-11-24 19:13 UTC, merged

2020-11-24 19:13 UTC, jonnydawg commented
👍